# cfn-lint configuration
# https://github.com/aws-cloudformation/cfn-lint

templates:
  - cloudformation/*.yaml

# Ignore rules that produce false positives for valid CloudFormation patterns
ignore_checks:
  # W1030: Ref validation when Fn::If branches have different parameter types
  # Our templates use conditional subnets (PublicSubnetIds vs SubnetIds) which
  # triggers false positives when cfn-lint evaluates the unused branch
  - W1030
