{
 "title": "RoboSystems Staging Logs",
 "tags": [
  "robosystems",
  "infrastructure",
  "staging"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   { "name": "period", "label": "Period [sec]", "query": "60,300,3600" }
  ]
 },
 "panels": [
  {
   "title": "API Logs",
   "type": "logs",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expression": "fields @timestamp, @message |\n filter strcontains(@logStream, \"/api\") |\n filter not strcontains(@message, \"opentelemetry.exporter.otlp.proto.http.trace_exporter\" |\n sort @timestamp desc |\n limit 100",
     "logGroups": [
      {
       "accountId": "821526227241",
       "arn": "arn:aws:logs:us-east-1:821526227241:log-group:/robosystems/staging/api:*",
       "name": "/robosystems/staging/api"
      }
     ],
     "queryMode": "Logs",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Dagster Logs",
   "type": "logs",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expression": "fields @timestamp, @message |\n sort @timestamp desc |\n limit 100",
     "logGroups": [
      {
       "accountId": "821526227241",
       "arn": "arn:aws:logs:us-east-1:821526227241:log-group:/robosystems/staging/dagster:*",
       "name": "/robosystems/staging/dagster"
      }
     ],
     "queryMode": "Logs",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Graph API Logs",
   "type": "logs",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expression": "fields @timestamp, @message |\n sort @timestamp desc |\n limit 100",
     "logGroups": [
      {
       "accountId": "821526227241",
       "arn": "arn:aws:logs:us-east-1:821526227241:log-group:/robosystems/staging/graph-api:*",
       "name": "/robosystems/staging/graph-api"
      }
     ],
     "queryMode": "Logs",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Lambda Logs",
   "type": "logs",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "expression": "fields @timestamp, @message |\n sort @timestamp desc |\n limit 100",
     "logGroups": [
      {
       "accountId": "821526227241",
       "arn": "arn:aws:logs:us-east-1:821526227241:log-group:/aws/lambda/RoboSystemsGraphInfraStaging-api-key-generator:*",
       "name": "/aws/lambda/RoboSystemsGraphInfraStaging-api-key-generator"
      },
      {
       "accountId": "821526227241",
       "arn": "arn:aws:logs:us-east-1:821526227241:log-group:/aws/lambda/RoboSystemsGraphInfraStaging-instance-monitor:*",
       "name": "/aws/lambda/RoboSystemsGraphInfraStaging-instance-monitor"
      },
      {
       "accountId": "821526227241",
       "arn": "arn:aws:logs:us-east-1:821526227241:log-group:/aws/lambda/RoboSystemsGraphVolumesStaging-snapshot-selector:*",
       "name": "/aws/lambda/RoboSystemsGraphVolumesStaging-snapshot-selector"
      },
      {
       "accountId": "821526227241",
       "arn": "arn:aws:logs:us-east-1:821526227241:log-group:/aws/lambda/RoboSystemsGraphVolumesStaging-volume-detachment:*",
       "name": "/aws/lambda/RoboSystemsGraphVolumesStaging-volume-detachment"
      },
      {
       "accountId": "821526227241",
       "arn": "arn:aws:logs:us-east-1:821526227241:log-group:/aws/lambda/RoboSystemsGraphVolumesStaging-volume-manager:*",
       "name": "/aws/lambda/RoboSystemsGraphVolumesStaging-volume-manager"
      },
      {
       "accountId": "821526227241",
       "arn": "arn:aws:logs:us-east-1:821526227241:log-group:/aws/lambda/RoboSystemsGraphVolumesStaging-volume-monitor:*",
       "name": "/aws/lambda/RoboSystemsGraphVolumesStaging-volume-monitor"
      },
      {
       "accountId": "821526227241",
       "arn": "arn:aws:logs:us-east-1:821526227241:log-group:/aws/lambda/RoboSystemsPostgresIAMStaging-init-lambda:*",
       "name": "/aws/lambda/RoboSystemsPostgresIAMStaging-init-lambda"
      },
      {
       "accountId": "821526227241",
       "arn": "arn:aws:logs:us-east-1:821526227241:log-group:/aws/lambda/RoboSystemsPostgresIAMStaging-postgres-rotation:*",
       "name": "/aws/lambda/RoboSystemsPostgresIAMStaging-postgres-rotation"
      },
      {
       "accountId": "821526227241",
       "arn": "arn:aws:logs:us-east-1:821526227241:log-group:/aws/lambda/RoboSystemsPostgresIAMStaging-secrets-update-lambda:*",
       "name": "/aws/lambda/RoboSystemsPostgresIAMStaging-secrets-update-lambda"
      },
      {
       "accountId": "821526227241",
       "arn": "arn:aws:logs:us-east-1:821526227241:log-group:/aws/lambda/RoboSystemsPostgresStaging-init-lambda:*",
       "name": "/aws/lambda/RoboSystemsPostgresStaging-init-lambda"
      },
      {
       "accountId": "821526227241",
       "arn": "arn:aws:logs:us-east-1:821526227241:log-group:/aws/lambda/RoboSystemsPostgresStaging-postgres-rotation:*",
       "name": "/aws/lambda/RoboSystemsPostgresStaging-postgres-rotation"
      },
      {
       "accountId": "821526227241",
       "arn": "arn:aws:logs:us-east-1:821526227241:log-group:/aws/lambda/RoboSystemsValkeyStaging-valkey-rotation:*",
       "name": "/aws/lambda/RoboSystemsValkeyStaging-valkey-rotation"
      }
     ],
     "queryMode": "Logs",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Incoming log events [count/sec]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "LogGroupName": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/Logs,LogGroupName} MetricName=\"IncomingLogEvents\"', 'Sum', $period))/$period",
     "metricName": "IncomingLogEvents",
     "namespace": "AWS/Logs",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Incoming bytes [bytes/sec]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "dimensions": { "LogGroupName": "*" },
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/Logs,LogGroupName} MetricName=\"IncomingBytes\"', 'Sum', $period))/$period",
     "metricEditorMode": 1,
     "metricName": "IncomingLogEvents",
     "namespace": "AWS/Logs",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Delivery errors [count]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "LogGroupName": "*" },
     "label": "Delivery Errors",
     "metricName": "DeliveryErrors",
     "namespace": "AWS/Logs",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LogGroupName": "*" },
     "label": "Delivery Throttling",
     "metricName": "DeliveryThrottling",
     "namespace": "AWS/Logs",
     "period": "$period",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  }
 ]
}